application: padlv-541
version: 1
runtime: go
api_version: go1

handlers:
- url: /[0-9]+
  script: _go_app

- url: /$
  static_files: static/index.html
  upload: static/index.html

- url: /(robots.txt|favicon.ico)$
  static_dir: static

